// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6V8g1C5CLPGaPffjUNDFYeqXdJYj9vrM',
    appId: '1:941368936387:web:1ae2758395f8f0493a5f76',
    messagingSenderId: '941368936387',
    projectId: 'pocketpharmaproject',
    authDomain: 'pocketpharmaproject.firebaseapp.com',
    storageBucket: 'pocketpharmaproject.appspot.com',
    measurementId: 'G-YV8691ZDY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb_sTfpDP_qnzzV2gVJop7TeYS09Ka8rw',
    appId: '1:941368936387:android:84bef931fce453933a5f76',
    messagingSenderId: '941368936387',
    projectId: 'pocketpharmaproject',
    storageBucket: 'pocketpharmaproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIuy9tCs11zyWalLLjDapgwWYtzXpTNzY',
    appId: '1:941368936387:ios:a52d8589287629563a5f76',
    messagingSenderId: '941368936387',
    projectId: 'pocketpharmaproject',
    storageBucket: 'pocketpharmaproject.appspot.com',
    iosClientId: '941368936387-24bvufcg9vrc1sjoont88123e1b8chb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketFarma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIuy9tCs11zyWalLLjDapgwWYtzXpTNzY',
    appId: '1:941368936387:ios:a52d8589287629563a5f76',
    messagingSenderId: '941368936387',
    projectId: 'pocketpharmaproject',
    storageBucket: 'pocketpharmaproject.appspot.com',
    iosClientId: '941368936387-24bvufcg9vrc1sjoont88123e1b8chb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketFarma',
  );
}
